# Generated by Django 5.0.4 on 2024-04-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accno', models.CharField(max_length=20)),
                ('ifsc', models.CharField(max_length=10)),
                ('balance', models.CharField(max_length=40)),
            ],
        ),
    ]
